apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sReadOnlyRootFS
metadata:
  name: require-readonly-rootfs
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "audit-zone"