apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdenyhostpath
spec:
  crd:
    spec:
      names:
        kind: K8sDenyHostPath
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdenyhostpath
        
        violation[{"msg": msg}] {
            volume := input.review.object.spec.volumes[_]
            volume.hostPath
            msg := sprintf("hostPath volumes are not allowed: %v", [volume.name])
        }